// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectWebApp.Models
{
    public partial class AppUser
    {
        public AppUser()
        {
            AppCategories = new HashSet<AppCategory>();
            AppLogs = new HashSet<AppLog>();
            Comments = new HashSet<Comment>();
            Documents = new HashSet<Document>();
            Notifications = new HashSet<Notification>();
            ServiceRequests = new HashSet<ServiceRequest>();

        }




        [Key]
        public int UserID { get; set; }

        [ForeignKey("UserRole")]
        public int UserRoleId { get; set; }
            public string Fname { get; set; }
            public string Lname { get; set; }
            public DateTime Dob { get; set; }
            public string Email { get; set; }
            public int Phone { get; set; } // Changed to string if it includes formatting
            public virtual UserRole UserRole { get; set; }
        

        public virtual ICollection<AppCategory> AppCategories { get; set; }
        public virtual ICollection<AppLog> AppLogs { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
