// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Humanizer;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration.CommandLine;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;

namespace ProjectWebApp.Models
{
    public partial class Comment
    {
        [Key]
        public int CommentId { get; set; }
        public DateTime CommentDateTime { get; set; }
        public int UserId { get; set; }
        public string CommentTitle { get; set; }
        public string CommentText { get; set; }

        [ForeignKey("ServiceRequest")]
        public int ServiceRequestId { get; set; }
        

        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual AppUser User { get; set; }
    }
}