// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectWebApp.Models
{
    public partial class Document
    {
        public Document()
        {
            ServiceRequests = new HashSet<ServiceRequest>();
        }
        [Key]
        public int DocumentId { get; set; }
        public string DocumentName { get; set; }
        public int UserId { get; set; }
        public DateTime UploadDate { get; set; }
        public string DocumentType { get; set; }
        public string DocumentDescription { get; set; }
        public string DocumentPath { get; set; }
        [ForeignKey("ServiceRequest")]
        public int ServiceRequestId { get; set; }

        public virtual AppUser User { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}