// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjectWebApp.Models
{
    public partial class UserRole
    {
        public UserRole()
        {
            AppUsers = new HashSet<AppUser>();
        }
        [Key]
        public int UserRoleId { get; set; }
        public string UserType { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
    public enum UserTypes
    {
        Admin,
        Manager,
        Technician,
        User
    }
}