// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCare.Models
{
    public partial class AppCategory
    {
        public AppCategory()
        {
            AppServices = new HashSet<AppService>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public int UserId { get; set; }

        public virtual AppUser User { get; set; }
        public virtual ICollection<AppService> AppServices { get; set; }
    }
}