// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCare.Models
{
    public partial class AppLog
    {
        public int LogId { get; set; }
        public string LogSource { get; set; }
        public string LogType { get; set; }
        public int UserId { get; set; }
        public DateTime LogDateTime { get; set; }
        public string LogMessage { get; set; }
        public string OriginalValue { get; set; }
        public string CurrentValue { get; set; }

        public virtual AppUser User { get; set; }
    }
}