// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCare.Models
{
    public partial class AppService
    {
        public AppService()
        {
            ServiceRequests = new HashSet<ServiceRequest>();
        }

        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string ServiceType { get; set; }
        public string ServiceDescription { get; set; }
        public int CategoryId { get; set; }
        public string ServiceDuration { get; set; }
        public double Price { get; set; }

        public virtual AppCategory Category { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        //public int Id { get; internal set; }
    }
}