// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCare.Models
{
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public string NotificationMessage { get; set; }
        public string NotificationType { get; set; }
        public DateTime NotificationDateTime { get; set; }
        public int? NotificationStatusId { get; set; }
        public int UserId { get; set; }

        public virtual NotificationStatus NotificationStatus { get; set; }
        public virtual AppUser User { get; set; }
    }
}