// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCare.Models
{
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public double Total { get; set; }
        public string PayType { get; set; }
        public int? ServiceRequestId { get; set; }
        public string Address { get; set; }
        public int PaymentStatusId { get; set; }
        public DateTime PayDateTime { get; set; }

        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}