// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCareObjects.Models
{
    public partial class Comment
    {
        public int CommentId { get; set; }
        public DateTime CommentDateTime { get; set; }
        public int UserId { get; set; }
        public string CommentTitle { get; set; }
        public string CommentText { get; set; }
        public int ServiceRequestId { get; set; }

        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual AppUser User { get; set; }
    }
}