// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCareObjects.Models
{
    public partial class NotificationStatus
    {
        public NotificationStatus()
        {
            Notifications = new HashSet<Notification>();
        }

        public int NotificationStatusId { get; set; }
        public string NotificationStatus1 { get; set; }

        public virtual ICollection<Notification> Notifications { get; set; }
    }
}