// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HouseCareObjects.Models
{
    public partial class PaymentStatus
    {
        public PaymentStatus()
        {
            Payments = new HashSet<Payment>();
        }

        public int PaymentStatusId { get; set; }
        public bool PaymentStatus1 { get; set; }

        public virtual ICollection<Payment> Payments { get; set; }
    }
}